@startuml

enum 客户类型 {
    企业
    个人
    集团
}

class 客户{
    客户编号
    客户名称
    统一社会信用代码
}

class 合同{
    合同编号
    合同金额
    签订时间
}

class 主合同

class 从合同

主合同 --|> 合同

从合同 --|> 合同

主合同 *-- 从合同

客户 -- "+type" 客户类型

客户 "+lessee 1" <-- "+contracts 0..*" 主合同
客户 "+lessor 1" <-- "+contracts 0..*" 主合同

从合同 --> 资产

class 租赁物 {
    （现）价值
}

class 担保物 {
    担保金额
}

租赁物 --|> 资产
担保物 --|> 资产

class 资产{
    资产编号
    类型
    状态
    （原）价值
}
@end